"""
Value Attribution System
========================

Expanded value categorization system with granular subcategories for
tracking the specific types of value generated by Auto-Claude features.

This module provides:
- ValueCategory enum with granular subcategories for execution, decision,
  prevention, and knowledge value types
- ValueAttribution dataclass for representing attributed value with evidence
- ValueAttributionService for mapping artifacts to value categories

Value Categories:
1. EXECUTION - Direct work done (code, boilerplate, refactoring)
2. DECISION - Strategic choices (feature prioritization, architecture, tech)
3. PREVENTION - Problems avoided (bugs, security, performance, rework)
4. KNOWLEDGE - Learning gained (docs, diagrams, onboarding, patterns)
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any


class ValueCategory(Enum):
    """
    Granular value categories with subcategories for detailed attribution.

    Parent types:
    - execution: Direct work value
    - decision: Strategic value
    - prevention: Problem avoidance
    - knowledge: Learning value
    """

    # Execution subcategories - direct work value
    CODE_GENERATED = "code_generated"
    BOILERPLATE_SAVED = "boilerplate_saved"
    REFACTORING_DONE = "refactoring_done"
    TESTS_WRITTEN = "tests_written"
    BUG_FIXED = "bug_fixed"

    # Decision subcategories - strategic value
    FEATURE_PRIORITIZED = "feature_prioritized"
    ARCHITECTURE_DECISION = "architecture_decision"
    TECHNOLOGY_CHOICE = "technology_choice"
    SCOPE_DECISION = "scope_decision"
    RISK_ASSESSMENT = "risk_assessment"

    # Prevention subcategories - problems avoided
    BUG_PREVENTED = "bug_prevented"
    SECURITY_ISSUE_FOUND = "security_issue_found"
    PERFORMANCE_ISSUE_FOUND = "performance_issue_found"
    REWORK_AVOIDED = "rework_avoided"
    TECH_DEBT_PREVENTED = "tech_debt_prevented"

    # Knowledge subcategories - learning value
    DOCUMENTATION_CREATED = "documentation_created"
    DIAGRAM_GENERATED = "diagram_generated"
    ONBOARDING_ACCELERATED = "onboarding_accelerated"
    PATTERN_DOCUMENTED = "pattern_documented"
    CODE_EXPLAINED = "code_explained"
    INSIGHT_DISCOVERED = "insight_discovered"


# Mapping from subcategory to parent type
CATEGORY_PARENT_MAP: Dict[ValueCategory, str] = {
    # Execution
    ValueCategory.CODE_GENERATED: "execution",
    ValueCategory.BOILERPLATE_SAVED: "execution",
    ValueCategory.REFACTORING_DONE: "execution",
    ValueCategory.TESTS_WRITTEN: "execution",
    ValueCategory.BUG_FIXED: "execution",

    # Decision
    ValueCategory.FEATURE_PRIORITIZED: "decision",
    ValueCategory.ARCHITECTURE_DECISION: "decision",
    ValueCategory.TECHNOLOGY_CHOICE: "decision",
    ValueCategory.SCOPE_DECISION: "decision",
    ValueCategory.RISK_ASSESSMENT: "decision",

    # Prevention
    ValueCategory.BUG_PREVENTED: "prevention",
    ValueCategory.SECURITY_ISSUE_FOUND: "prevention",
    ValueCategory.PERFORMANCE_ISSUE_FOUND: "prevention",
    ValueCategory.REWORK_AVOIDED: "prevention",
    ValueCategory.TECH_DEBT_PREVENTED: "prevention",

    # Knowledge
    ValueCategory.DOCUMENTATION_CREATED: "knowledge",
    ValueCategory.DIAGRAM_GENERATED: "knowledge",
    ValueCategory.ONBOARDING_ACCELERATED: "knowledge",
    ValueCategory.PATTERN_DOCUMENTED: "knowledge",
    ValueCategory.CODE_EXPLAINED: "knowledge",
    ValueCategory.INSIGHT_DISCOVERED: "knowledge",
}


# Default value per category (in USD)
# These can be overridden in configuration
DEFAULT_VALUES: Dict[ValueCategory, float] = {
    # Execution values
    ValueCategory.CODE_GENERATED: 50.0,  # Per 100 lines
    ValueCategory.BOILERPLATE_SAVED: 25.0,  # Per component/file
    ValueCategory.REFACTORING_DONE: 100.0,  # Per refactoring task
    ValueCategory.TESTS_WRITTEN: 75.0,  # Per test file
    ValueCategory.BUG_FIXED: 150.0,  # Per bug

    # Decision values
    ValueCategory.FEATURE_PRIORITIZED: 100.0,  # Per feature decision
    ValueCategory.ARCHITECTURE_DECISION: 500.0,  # Per major decision
    ValueCategory.TECHNOLOGY_CHOICE: 200.0,  # Per tech decision
    ValueCategory.SCOPE_DECISION: 150.0,  # Per scope change
    ValueCategory.RISK_ASSESSMENT: 100.0,  # Per risk identified

    # Prevention values (typically higher due to cost of issues in production)
    ValueCategory.BUG_PREVENTED: 500.0,  # Per bug prevented
    ValueCategory.SECURITY_ISSUE_FOUND: 2000.0,  # Per security issue
    ValueCategory.PERFORMANCE_ISSUE_FOUND: 500.0,  # Per perf issue
    ValueCategory.REWORK_AVOIDED: 300.0,  # Per rework task avoided
    ValueCategory.TECH_DEBT_PREVENTED: 200.0,  # Per debt item prevented

    # Knowledge values
    ValueCategory.DOCUMENTATION_CREATED: 50.0,  # Per doc
    ValueCategory.DIAGRAM_GENERATED: 75.0,  # Per diagram
    ValueCategory.ONBOARDING_ACCELERATED: 100.0,  # Per onboarding session
    ValueCategory.PATTERN_DOCUMENTED: 150.0,  # Per pattern
    ValueCategory.CODE_EXPLAINED: 25.0,  # Per explanation
    ValueCategory.INSIGHT_DISCOVERED: 50.0,  # Per insight
}


@dataclass
class ValueAttribution:
    """
    Represents a value attribution for a specific artifact or action.

    Attributes:
        category: The granular value category
        parent_type: The parent type (execution, decision, prevention, knowledge)
        value_usd: The estimated value in USD
        confidence: Confidence score (0-1) for the attribution
        evidence: List of links/references to artifacts or traces that support this attribution
        metadata: Additional metadata about the attribution
        timestamp: When the value was attributed
    """
    category: ValueCategory
    parent_type: str
    value_usd: float
    confidence: float = 0.8
    evidence: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def __post_init__(self):
        """Ensure parent_type matches category if not provided."""
        if not self.parent_type:
            self.parent_type = CATEGORY_PARENT_MAP.get(self.category, "other")

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "category": self.category.value,
            "parent_type": self.parent_type,
            "value_usd": self.value_usd,
            "confidence": self.confidence,
            "evidence": self.evidence,
            "metadata": self.metadata,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class ValueBreakdownExpanded:
    """
    Expanded value breakdown with subcategory details.

    Contains aggregated values by parent type and detailed
    breakdown by subcategory.
    """
    # Parent type totals
    execution_value: float = 0.0
    decision_value: float = 0.0
    prevention_value: float = 0.0
    knowledge_value: float = 0.0

    # Subcategory breakdowns
    by_subcategory: Dict[str, float] = field(default_factory=dict)

    # Attribution details
    attributions: List[ValueAttribution] = field(default_factory=list)

    @property
    def total_value(self) -> float:
        """Calculate total value across all categories."""
        return (
            self.execution_value +
            self.decision_value +
            self.prevention_value +
            self.knowledge_value
        )

    def add_attribution(self, attribution: ValueAttribution) -> None:
        """Add an attribution and update totals."""
        self.attributions.append(attribution)

        # Update subcategory
        cat_key = attribution.category.value
        self.by_subcategory[cat_key] = self.by_subcategory.get(cat_key, 0) + attribution.value_usd

        # Update parent type total
        if attribution.parent_type == "execution":
            self.execution_value += attribution.value_usd
        elif attribution.parent_type == "decision":
            self.decision_value += attribution.value_usd
        elif attribution.parent_type == "prevention":
            self.prevention_value += attribution.value_usd
        elif attribution.parent_type == "knowledge":
            self.knowledge_value += attribution.value_usd

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "execution_value": self.execution_value,
            "decision_value": self.decision_value,
            "prevention_value": self.prevention_value,
            "knowledge_value": self.knowledge_value,
            "total_value": self.total_value,
            "by_subcategory": self.by_subcategory,
            "attribution_count": len(self.attributions),
        }


# Artifact type to value category mapping
ARTIFACT_TYPE_MAPPING: Dict[str, ValueCategory] = {
    # Code and Implementation
    "code_implementation": ValueCategory.CODE_GENERATED,
    "refactoring": ValueCategory.REFACTORING_DONE,
    "test_written": ValueCategory.TESTS_WRITTEN,
    "bug_fix": ValueCategory.BUG_FIXED,
    "fix_applied": ValueCategory.BUG_FIXED,
    "boilerplate": ValueCategory.BOILERPLATE_SAVED,

    # Decision artifacts
    "implementation_plan": ValueCategory.ARCHITECTURE_DECISION,
    "architecture_decision": ValueCategory.ARCHITECTURE_DECISION,
    "subtask_definition": ValueCategory.SCOPE_DECISION,
    "risk_assessment": ValueCategory.RISK_ASSESSMENT,
    "roadmap_feature": ValueCategory.FEATURE_PRIORITIZED,
    "idea": ValueCategory.FEATURE_PRIORITIZED,
    "priority_assignment": ValueCategory.FEATURE_PRIORITIZED,
    "technology_choice": ValueCategory.TECHNOLOGY_CHOICE,

    # Prevention artifacts
    "security_finding": ValueCategory.SECURITY_ISSUE_FOUND,
    "security_issue": ValueCategory.SECURITY_ISSUE_FOUND,
    "security_audit": ValueCategory.SECURITY_ISSUE_FOUND,
    "bug_detected": ValueCategory.BUG_PREVENTED,
    "qa_finding": ValueCategory.BUG_PREVENTED,
    "performance_bottleneck": ValueCategory.PERFORMANCE_ISSUE_FOUND,
    "performance_insight": ValueCategory.PERFORMANCE_ISSUE_FOUND,
    "tech_debt_item": ValueCategory.TECH_DEBT_PREVENTED,

    # Knowledge artifacts
    "documentation": ValueCategory.DOCUMENTATION_CREATED,
    "spec_document": ValueCategory.DOCUMENTATION_CREATED,
    "diagram": ValueCategory.DIAGRAM_GENERATED,
    "code_example": ValueCategory.CODE_EXPLAINED,
    "code_explanation": ValueCategory.CODE_EXPLAINED,
    "pattern_discovered": ValueCategory.PATTERN_DOCUMENTED,
    "best_practice": ValueCategory.PATTERN_DOCUMENTED,
    "architecture_insight": ValueCategory.INSIGHT_DISCOVERED,
    "recommendation": ValueCategory.INSIGHT_DISCOVERED,
    "lesson_learned": ValueCategory.INSIGHT_DISCOVERED,
    "gotcha_identified": ValueCategory.INSIGHT_DISCOVERED,
}


class ValueAttributionService:
    """
    Service for attributing value to artifacts and actions.

    Maps artifact types to value categories and calculates
    the business value based on configurable multipliers.
    """

    def __init__(
        self,
        value_overrides: Optional[Dict[ValueCategory, float]] = None,
        hourly_rate: float = 150.0,
    ):
        """
        Initialize the value attribution service.

        Args:
            value_overrides: Optional overrides for default values per category
            hourly_rate: Developer hourly rate for time-based calculations
        """
        self.values = {**DEFAULT_VALUES}
        if value_overrides:
            self.values.update(value_overrides)
        self.hourly_rate = hourly_rate

    def attribute_value(
        self,
        artifact_type: str,
        content: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ValueAttribution:
        """
        Attribute value to an artifact based on its type and content.

        Args:
            artifact_type: The type of artifact (e.g., "code_implementation")
            content: The artifact content
            metadata: Additional metadata about the artifact

        Returns:
            ValueAttribution with calculated value and category
        """
        metadata = metadata or {}

        # Map artifact type to category
        category = ARTIFACT_TYPE_MAPPING.get(
            artifact_type,
            self._infer_category_from_content(content, artifact_type)
        )

        # Calculate value based on category and content
        value_usd = self._calculate_value(category, content, metadata)

        # Calculate confidence based on available evidence
        confidence = self._calculate_confidence(category, content, metadata)

        # Build evidence list
        evidence = self._build_evidence(metadata)

        return ValueAttribution(
            category=category,
            parent_type=CATEGORY_PARENT_MAP.get(category, "other"),
            value_usd=value_usd,
            confidence=confidence,
            evidence=evidence,
            metadata=metadata,
        )

    def _infer_category_from_content(
        self,
        content: str,
        artifact_type: str,
    ) -> ValueCategory:
        """Infer category from content when type is not mapped."""
        content_lower = content.lower()

        # Check for security-related content
        if any(kw in content_lower for kw in ["security", "vulnerability", "exploit", "injection"]):
            return ValueCategory.SECURITY_ISSUE_FOUND

        # Check for performance content
        if any(kw in content_lower for kw in ["performance", "latency", "bottleneck", "slow"]):
            return ValueCategory.PERFORMANCE_ISSUE_FOUND

        # Check for documentation content
        if any(kw in content_lower for kw in ["documentation", "readme", "guide", "tutorial"]):
            return ValueCategory.DOCUMENTATION_CREATED

        # Check for diagram content
        if any(kw in content_lower for kw in ["mermaid", "diagram", "flowchart", "graph"]):
            return ValueCategory.DIAGRAM_GENERATED

        # Check for code patterns
        if any(kw in content_lower for kw in ["pattern", "best practice", "convention"]):
            return ValueCategory.PATTERN_DOCUMENTED

        # Check for test content
        if any(kw in content_lower for kw in ["test", "spec", "assert", "expect"]):
            return ValueCategory.TESTS_WRITTEN

        # Default to insight for unclassified content
        return ValueCategory.INSIGHT_DISCOVERED

    def _calculate_value(
        self,
        category: ValueCategory,
        content: str,
        metadata: Dict[str, Any],
    ) -> float:
        """Calculate value based on category and content metrics."""
        base_value = self.values.get(category, 50.0)

        # Apply content-based multipliers
        multiplier = 1.0

        # Length-based multiplier for documentation and code
        content_length = len(content)
        if category in [
            ValueCategory.CODE_GENERATED,
            ValueCategory.DOCUMENTATION_CREATED,
            ValueCategory.CODE_EXPLAINED,
        ]:
            if content_length > 1000:
                multiplier *= 1.5
            elif content_length > 500:
                multiplier *= 1.2

        # Impact-based multiplier from metadata
        impact = metadata.get("impact", "medium")
        if impact == "high":
            multiplier *= 2.0
        elif impact == "critical":
            multiplier *= 3.0
        elif impact == "low":
            multiplier *= 0.5

        # Priority-based multiplier
        priority = metadata.get("priority", "")
        if priority in ["must", "critical"]:
            multiplier *= 1.5
        elif priority in ["could", "wont"]:
            multiplier *= 0.7

        # Severity multiplier for prevention categories
        severity = metadata.get("severity", "")
        if category in [
            ValueCategory.SECURITY_ISSUE_FOUND,
            ValueCategory.BUG_PREVENTED,
            ValueCategory.PERFORMANCE_ISSUE_FOUND,
        ]:
            if severity == "critical":
                multiplier *= 5.0
            elif severity == "high":
                multiplier *= 2.0
            elif severity == "low":
                multiplier *= 0.3

        return round(base_value * multiplier, 2)

    def _calculate_confidence(
        self,
        category: ValueCategory,
        content: str,
        metadata: Dict[str, Any],
    ) -> float:
        """Calculate confidence score for the attribution."""
        confidence = 0.7  # Base confidence

        # Higher confidence for artifacts with clear type mapping
        if ARTIFACT_TYPE_MAPPING.get(metadata.get("type", "")) == category:
            confidence += 0.1

        # Higher confidence when we have supporting evidence
        if metadata.get("trace_id"):
            confidence += 0.05
        if metadata.get("artifact_id"):
            confidence += 0.05
        if metadata.get("spec_id"):
            confidence += 0.05

        # Content-based confidence adjustments
        content_lower = content.lower()

        # Higher confidence for specific technical content
        if category == ValueCategory.SECURITY_ISSUE_FOUND:
            if any(kw in content_lower for kw in ["cve", "owasp", "vulnerability"]):
                confidence += 0.1

        if category == ValueCategory.DIAGRAM_GENERATED:
            if "mermaid" in content_lower or "```" in content:
                confidence += 0.1

        return min(confidence, 1.0)

    def _build_evidence(self, metadata: Dict[str, Any]) -> List[str]:
        """Build list of evidence references from metadata."""
        evidence = []

        if trace_id := metadata.get("trace_id"):
            evidence.append(f"trace:{trace_id}")

        if artifact_id := metadata.get("artifact_id") or metadata.get("id"):
            evidence.append(f"artifact:{artifact_id}")

        if spec_id := metadata.get("spec_id"):
            evidence.append(f"spec:{spec_id}")

        if storage_path := metadata.get("storage_path"):
            evidence.append(f"file:{storage_path}")

        return evidence

    def attribute_artifacts(
        self,
        artifacts: List[Dict[str, Any]],
    ) -> ValueBreakdownExpanded:
        """
        Attribute value to a list of artifacts.

        Args:
            artifacts: List of artifact dictionaries

        Returns:
            ValueBreakdownExpanded with aggregated values
        """
        breakdown = ValueBreakdownExpanded()

        for artifact in artifacts:
            artifact_type = artifact.get("type", "unknown")
            content = artifact.get("content", "")

            attribution = self.attribute_value(
                artifact_type=artifact_type,
                content=content,
                metadata=artifact,
            )

            breakdown.add_attribution(attribution)

        return breakdown

    def get_breakdown_by_project(
        self,
        attributions: List[ValueAttribution],
    ) -> Dict[str, ValueBreakdownExpanded]:
        """
        Group attributions by project and return breakdowns.

        Args:
            attributions: List of ValueAttribution objects

        Returns:
            Dictionary mapping project_id to ValueBreakdownExpanded
        """
        by_project: Dict[str, ValueBreakdownExpanded] = {}

        for attr in attributions:
            project_id = attr.metadata.get("project_id", "default")

            if project_id not in by_project:
                by_project[project_id] = ValueBreakdownExpanded()

            by_project[project_id].add_attribution(attr)

        return by_project

    def get_breakdown_by_feature_type(
        self,
        attributions: List[ValueAttribution],
    ) -> Dict[str, ValueBreakdownExpanded]:
        """
        Group attributions by feature type (build, spec, insights, etc.).

        Args:
            attributions: List of ValueAttribution objects

        Returns:
            Dictionary mapping feature_type to ValueBreakdownExpanded
        """
        by_feature: Dict[str, ValueBreakdownExpanded] = {}

        for attr in attributions:
            feature_type = attr.metadata.get("feature_type", "other")

            if feature_type not in by_feature:
                by_feature[feature_type] = ValueBreakdownExpanded()

            by_feature[feature_type].add_attribution(attr)

        return by_feature
