"""
Unified ROI Model
==================

Defines a universal ROI structure that works across all Auto-Claude features:
- Ideation (code improvements, security, performance, etc.)
- Roadmap (feature prioritization, strategic decisions)
- Spec (requirements clarity, reduced rework)
- Build (code generation, dev hours saved)
- QA (bugs prevented, quality assurance)
- GitHub (PR review, issue triage)
- Insights (codebase exploration, knowledge transfer)

Each feature type contributes to ROI in different ways:
1. EXECUTION_VALUE: Direct value from work done (code generated, hours saved)
2. DECISION_VALUE: Value from making/not making decisions (prioritization, viability)
3. PREVENTION_VALUE: Value from preventing problems (bugs, security issues)
4. KNOWLEDGE_VALUE: Value from knowledge gain (insights, exploration)
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any, TYPE_CHECKING

if TYPE_CHECKING:
    from analytics.squad_config import SquadConfig


class ValueType(Enum):
    """Type of value generated by a feature."""
    EXECUTION = "execution"      # Direct work value (code, implementation)
    DECISION = "decision"        # Strategic value (prioritization, viability)
    PREVENTION = "prevention"    # Problem avoidance (bugs, security)
    KNOWLEDGE = "knowledge"      # Learning value (insights, exploration)


class ValueSubcategory(Enum):
    """
    Granular value subcategories for detailed attribution.
    Maps to parent ValueType categories.
    """
    # Execution subcategories
    CODE_GENERATED = "code_generated"
    BOILERPLATE_SAVED = "boilerplate_saved"
    REFACTORING_DONE = "refactoring_done"
    TESTS_WRITTEN = "tests_written"
    BUG_FIXED = "bug_fixed"

    # Decision subcategories
    FEATURE_PRIORITIZED = "feature_prioritized"
    ARCHITECTURE_DECISION = "architecture_decision"
    TECHNOLOGY_CHOICE = "technology_choice"
    SCOPE_DECISION = "scope_decision"
    RISK_ASSESSMENT = "risk_assessment"

    # Prevention subcategories
    BUG_PREVENTED = "bug_prevented"
    SECURITY_ISSUE_FOUND = "security_issue_found"
    PERFORMANCE_ISSUE_FOUND = "performance_issue_found"
    REWORK_AVOIDED = "rework_avoided"
    TECH_DEBT_PREVENTED = "tech_debt_prevented"

    # Knowledge subcategories
    DOCUMENTATION_CREATED = "documentation_created"
    DIAGRAM_GENERATED = "diagram_generated"
    ONBOARDING_ACCELERATED = "onboarding_accelerated"
    PATTERN_DOCUMENTED = "pattern_documented"
    CODE_EXPLAINED = "code_explained"
    INSIGHT_DISCOVERED = "insight_discovered"


# Mapping from subcategory to parent ValueType
SUBCATEGORY_TO_PARENT: Dict[ValueSubcategory, ValueType] = {
    # Execution
    ValueSubcategory.CODE_GENERATED: ValueType.EXECUTION,
    ValueSubcategory.BOILERPLATE_SAVED: ValueType.EXECUTION,
    ValueSubcategory.REFACTORING_DONE: ValueType.EXECUTION,
    ValueSubcategory.TESTS_WRITTEN: ValueType.EXECUTION,
    ValueSubcategory.BUG_FIXED: ValueType.EXECUTION,

    # Decision
    ValueSubcategory.FEATURE_PRIORITIZED: ValueType.DECISION,
    ValueSubcategory.ARCHITECTURE_DECISION: ValueType.DECISION,
    ValueSubcategory.TECHNOLOGY_CHOICE: ValueType.DECISION,
    ValueSubcategory.SCOPE_DECISION: ValueType.DECISION,
    ValueSubcategory.RISK_ASSESSMENT: ValueType.DECISION,

    # Prevention
    ValueSubcategory.BUG_PREVENTED: ValueType.PREVENTION,
    ValueSubcategory.SECURITY_ISSUE_FOUND: ValueType.PREVENTION,
    ValueSubcategory.PERFORMANCE_ISSUE_FOUND: ValueType.PREVENTION,
    ValueSubcategory.REWORK_AVOIDED: ValueType.PREVENTION,
    ValueSubcategory.TECH_DEBT_PREVENTED: ValueType.PREVENTION,

    # Knowledge
    ValueSubcategory.DOCUMENTATION_CREATED: ValueType.KNOWLEDGE,
    ValueSubcategory.DIAGRAM_GENERATED: ValueType.KNOWLEDGE,
    ValueSubcategory.ONBOARDING_ACCELERATED: ValueType.KNOWLEDGE,
    ValueSubcategory.PATTERN_DOCUMENTED: ValueType.KNOWLEDGE,
    ValueSubcategory.CODE_EXPLAINED: ValueType.KNOWLEDGE,
    ValueSubcategory.INSIGHT_DISCOVERED: ValueType.KNOWLEDGE,
}


@dataclass
class SubcategoryValue:
    """Value for a specific subcategory with confidence and evidence."""
    subcategory: ValueSubcategory
    value_usd: float
    confidence: float = 0.8
    count: int = 1  # Number of attributions for this subcategory
    evidence: List[str] = field(default_factory=list)


@dataclass
class ValueBreakdownExpanded:
    """
    Expanded value breakdown with subcategory details.

    Extends the basic ValueBreakdown with granular subcategory tracking.
    """
    # Parent type totals
    execution_value: float = 0.0
    decision_value: float = 0.0
    prevention_value: float = 0.0
    knowledge_value: float = 0.0

    # Subcategory details
    by_subcategory: Dict[str, SubcategoryValue] = field(default_factory=dict)

    @property
    def total_value(self) -> float:
        """Calculate total value across all categories."""
        return (
            self.execution_value +
            self.decision_value +
            self.prevention_value +
            self.knowledge_value
        )

    def add_subcategory_value(
        self,
        subcategory: ValueSubcategory,
        value_usd: float,
        confidence: float = 0.8,
        evidence: Optional[List[str]] = None,
    ) -> None:
        """Add value for a specific subcategory."""
        key = subcategory.value
        evidence = evidence or []

        if key in self.by_subcategory:
            existing = self.by_subcategory[key]
            existing.value_usd += value_usd
            existing.count += 1
            existing.confidence = (existing.confidence + confidence) / 2
            existing.evidence.extend(evidence)
        else:
            self.by_subcategory[key] = SubcategoryValue(
                subcategory=subcategory,
                value_usd=value_usd,
                confidence=confidence,
                count=1,
                evidence=evidence,
            )

        # Update parent totals
        parent = SUBCATEGORY_TO_PARENT.get(subcategory)
        if parent == ValueType.EXECUTION:
            self.execution_value += value_usd
        elif parent == ValueType.DECISION:
            self.decision_value += value_usd
        elif parent == ValueType.PREVENTION:
            self.prevention_value += value_usd
        elif parent == ValueType.KNOWLEDGE:
            self.knowledge_value += value_usd

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for API response."""
        return {
            "execution_value": self.execution_value,
            "decision_value": self.decision_value,
            "prevention_value": self.prevention_value,
            "knowledge_value": self.knowledge_value,
            "total_value": self.total_value,
            "by_subcategory": {
                key: {
                    "subcategory": val.subcategory.value,
                    "value_usd": val.value_usd,
                    "confidence": val.confidence,
                    "count": val.count,
                    "evidence_count": len(val.evidence),
                }
                for key, val in self.by_subcategory.items()
            },
        }


class FeatureType(Enum):
    """Types of features that generate ROI."""
    # Ideation
    IDEATION_CODE = "ideation_code_improvements"
    IDEATION_SECURITY = "ideation_security"
    IDEATION_PERFORMANCE = "ideation_performance"
    IDEATION_DOCUMENTATION = "ideation_documentation"
    IDEATION_UI_UX = "ideation_ui_ux"
    IDEATION_QUALITY = "ideation_code_quality"

    # Roadmap
    ROADMAP_DISCOVERY = "roadmap_discovery"
    ROADMAP_FEATURES = "roadmap_features"
    ROADMAP_COMPETITOR = "roadmap_competitor_analysis"

    # Spec
    SPEC_GATHERER = "spec_gatherer"
    SPEC_RESEARCHER = "spec_researcher"
    SPEC_WRITER = "spec_writer"
    SPEC_CRITIC = "spec_critic"

    # Build
    BUILD_PLANNER = "build_planner"
    BUILD_CODER = "build_coder"
    BUILD_QA_REVIEWER = "build_qa_reviewer"
    BUILD_QA_FIXER = "build_qa_fixer"

    # GitHub
    GITHUB_PR_REVIEW = "github_pr_review"
    GITHUB_ISSUE_TRIAGE = "github_issue_triage"
    GITHUB_BATCH_ISSUES = "github_batch_issues"

    # Insights
    INSIGHTS_CHAT = "insights_chat"
    INSIGHTS_ANALYZER = "insights_analyzer"

    # Merge
    MERGE_RESOLVER = "merge_resolver"

    # Other
    OTHER = "other"


@dataclass
class CostMetrics:
    """Cost metrics for any feature."""
    total_tokens: int = 0
    input_tokens: int = 0
    output_tokens: int = 0
    total_cost_usd: float = 0.0
    duration_seconds: float = 0.0
    model: str = ""


@dataclass
class IdeationMetrics:
    """Metrics specific to ideation features."""
    ideas_generated: int = 0
    high_impact_ideas: int = 0
    ideas_implemented: int = 0  # How many became specs
    categories: List[str] = field(default_factory=list)

    # Value estimation
    estimated_bug_prevention_value: float = 0.0  # Security issues found
    estimated_performance_gain_value: float = 0.0  # Performance improvements
    estimated_tech_debt_reduction: float = 0.0  # Refactoring value


@dataclass
class RoadmapMetrics:
    """Metrics specific to roadmap features."""
    features_identified: int = 0
    features_prioritized: int = 0
    features_rejected: int = 0  # "Not doing" decisions

    # Value estimation
    estimated_value_of_prioritization: float = 0.0  # Value of doing A before B
    estimated_value_of_rejection: float = 0.0  # Value of NOT doing something
    competitor_insights: int = 0


@dataclass
class SpecMetrics:
    """Metrics specific to spec creation."""
    phases_completed: int = 0
    requirements_gathered: int = 0
    complexity_level: str = "standard"  # simple, standard, complex

    # Quality indicators
    spec_clarity_score: float = 0.0  # 0-1, estimated from subsequent QA success
    refinement_iterations: int = 0  # How many times spec was revised


@dataclass
class BuildMetrics:
    """Metrics specific to build (code generation)."""
    lines_added: int = 0
    lines_removed: int = 0
    files_changed: int = 0
    subtasks_completed: int = 0
    subtasks_total: int = 0

    # Quality indicators
    qa_attempts: int = 0
    qa_passed: bool = False
    first_pass_success: bool = False  # Passed QA on first try


@dataclass
class GitHubMetrics:
    """Metrics specific to GitHub automation."""
    prs_reviewed: int = 0
    issues_triaged: int = 0
    issues_auto_fixed: int = 0
    duplicates_detected: int = 0
    spam_detected: int = 0

    # Time savings
    estimated_review_time_saved_minutes: float = 0.0
    estimated_triage_time_saved_minutes: float = 0.0


@dataclass
class InsightsMetrics:
    """Metrics specific to insights/chat features."""
    messages_exchanged: int = 0
    tasks_suggested: int = 0
    tasks_accepted: int = 0
    files_explored: int = 0

    # Knowledge value
    estimated_exploration_time_saved_minutes: float = 0.0


@dataclass
class MergeMetrics:
    """Metrics specific to merge conflict resolution."""
    conflicts_resolved: int = 0
    files_merged: int = 0
    manual_intervention_avoided: int = 0
    merge_decisions: int = 0  # ours/theirs/combined decisions
    code_choices: int = 0  # code choice decisions made

    # Time savings
    estimated_resolution_time_saved_minutes: float = 0.0


@dataclass
class UnifiedROI:
    """
    Universal ROI structure for any Auto-Claude feature.

    This model captures value across all dimensions:
    - Execution (direct work done)
    - Decision (strategic choices made)
    - Prevention (problems avoided)
    - Knowledge (learning gained)
    """
    # Identification
    feature_type: FeatureType
    spec_id: Optional[str] = None
    project_id: Optional[str] = None
    trace_id: Optional[str] = None
    timestamp: datetime = field(default_factory=datetime.utcnow)

    # Cost (universal)
    cost: CostMetrics = field(default_factory=CostMetrics)

    # Value breakdown by type
    value_breakdown: Dict[ValueType, float] = field(default_factory=dict)

    # Feature-specific metrics (only one will be populated)
    ideation_metrics: Optional[IdeationMetrics] = None
    roadmap_metrics: Optional[RoadmapMetrics] = None
    spec_metrics: Optional[SpecMetrics] = None
    build_metrics: Optional[BuildMetrics] = None
    github_metrics: Optional[GitHubMetrics] = None
    insights_metrics: Optional[InsightsMetrics] = None
    merge_metrics: Optional[MergeMetrics] = None

    # Calculated fields
    total_value_usd: float = 0.0
    roi_percentage: float = 0.0
    confidence_score: float = 0.0  # 0-1, how confident we are in the estimate

    # Additional metadata
    tags: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def calculate_total_value(self) -> float:
        """Calculate total value from all value types."""
        self.total_value_usd = sum(self.value_breakdown.values())
        return self.total_value_usd

    def calculate_roi(self) -> float:
        """Calculate ROI percentage."""
        if self.cost.total_cost_usd > 0:
            self.roi_percentage = (
                (self.total_value_usd - self.cost.total_cost_usd)
                / self.cost.total_cost_usd * 100
            )
        else:
            self.roi_percentage = 0.0 if self.total_value_usd == 0 else float('inf')
        return self.roi_percentage

    def to_langfuse_scores(self) -> Dict[str, float]:
        """Convert to Langfuse score format for storage."""
        scores = {
            "roi_percentage": self.roi_percentage,
            "total_value_usd": self.total_value_usd,
            "total_cost_usd": self.cost.total_cost_usd,
            "confidence_score": self.confidence_score,
        }

        # Add value breakdown
        for value_type, value in self.value_breakdown.items():
            scores[f"value_{value_type.value}_usd"] = value

        # Add feature-specific metrics
        if self.build_metrics:
            scores["lines_added"] = float(self.build_metrics.lines_added)
            scores["lines_removed"] = float(self.build_metrics.lines_removed)
            scores["files_changed"] = float(self.build_metrics.files_changed)
            scores["qa_attempts"] = float(self.build_metrics.qa_attempts)
            scores["qa_passed"] = 1.0 if self.build_metrics.qa_passed else 0.0

        if self.ideation_metrics:
            scores["ideas_generated"] = float(self.ideation_metrics.ideas_generated)
            scores["high_impact_ideas"] = float(self.ideation_metrics.high_impact_ideas)

        if self.roadmap_metrics:
            scores["features_identified"] = float(self.roadmap_metrics.features_identified)
            scores["features_rejected"] = float(self.roadmap_metrics.features_rejected)

        if self.github_metrics:
            scores["prs_reviewed"] = float(self.github_metrics.prs_reviewed)
            scores["issues_triaged"] = float(self.github_metrics.issues_triaged)

        if self.merge_metrics:
            scores["conflicts_resolved"] = float(self.merge_metrics.conflicts_resolved)
            scores["files_merged"] = float(self.merge_metrics.files_merged)
            scores["manual_intervention_avoided"] = float(self.merge_metrics.manual_intervention_avoided)
            scores["merge_decisions"] = float(self.merge_metrics.merge_decisions)
            scores["code_choices"] = float(self.merge_metrics.code_choices)

        return scores


# =============================================================================
# Value Estimation Constants (Defaults - can be overridden by SquadConfig)
# =============================================================================

# Hourly rate for developer time (configurable via SquadConfig)
DEFAULT_HOURLY_RATE = 150.0

# Value multipliers by feature type (can be overridden by squad.feature_multipliers)
VALUE_MULTIPLIERS = {
    # Ideation - value of finding problems early
    FeatureType.IDEATION_SECURITY: 5.0,  # Security issues are high value
    FeatureType.IDEATION_PERFORMANCE: 2.0,
    FeatureType.IDEATION_CODE: 1.5,
    FeatureType.IDEATION_DOCUMENTATION: 1.0,
    FeatureType.IDEATION_UI_UX: 1.5,
    FeatureType.IDEATION_QUALITY: 2.0,

    # Roadmap - value of strategic decisions
    FeatureType.ROADMAP_DISCOVERY: 1.5,
    FeatureType.ROADMAP_FEATURES: 2.0,
    FeatureType.ROADMAP_COMPETITOR: 1.5,

    # Spec - value of clarity (reduces rework)
    FeatureType.SPEC_GATHERER: 1.2,
    FeatureType.SPEC_RESEARCHER: 1.5,
    FeatureType.SPEC_WRITER: 1.5,
    FeatureType.SPEC_CRITIC: 2.0,  # Self-critique catches issues early

    # Build - direct execution value
    FeatureType.BUILD_PLANNER: 1.0,
    FeatureType.BUILD_CODER: 1.0,
    FeatureType.BUILD_QA_REVIEWER: 1.5,  # QA prevents bugs
    FeatureType.BUILD_QA_FIXER: 1.2,

    # GitHub - automation value
    FeatureType.GITHUB_PR_REVIEW: 1.5,
    FeatureType.GITHUB_ISSUE_TRIAGE: 1.2,
    FeatureType.GITHUB_BATCH_ISSUES: 2.0,

    # Insights - knowledge value
    FeatureType.INSIGHTS_CHAT: 1.0,
    FeatureType.INSIGHTS_ANALYZER: 1.5,

    # Merge - automation value (conflict resolution is high value)
    FeatureType.MERGE_RESOLVER: 2.0,
}

# Estimated time savings by action (in minutes)
TIME_SAVINGS = {
    "pr_review": 30,  # Average time to review a PR
    "issue_triage": 10,  # Average time to triage an issue
    "idea_generation": 60,  # Time to brainstorm ideas manually
    "roadmap_planning": 120,  # Time to plan roadmap manually
    "spec_writing": 180,  # Time to write a spec manually
    "codebase_exploration": 45,  # Time to explore unfamiliar codebase
    "conflict_resolution": 20,  # Average time to manually resolve a merge conflict
}

# Bug/issue prevention values (estimated cost of bug in production)
# Can be overridden by squad.prevention_values
PREVENTION_VALUES = {
    "security_critical": 10000.0,
    "security_high": 5000.0,
    "security_medium": 1000.0,
    "performance_critical": 5000.0,
    "performance_high": 2000.0,
    "bug_critical": 3000.0,
    "bug_high": 1000.0,
    "bug_medium": 300.0,
}


# =============================================================================
# Squad-aware Helper Functions
# =============================================================================

def get_hourly_rate(
    squad_config: Optional["SquadConfig"] = None,
    seniority: Optional[str] = None,
    role: Optional[str] = None,
) -> float:
    """
    Get hourly rate, optionally from squad config.

    Args:
        squad_config: Optional SquadConfig from the project's squad
        seniority: Stakeholder seniority (junior, mid, senior, staff, principal)
        role: Stakeholder role (developer, qa, devops, pm, architect, tech_lead)

    Returns:
        Hourly rate in USD
    """
    if squad_config:
        return squad_config.get_hourly_rate(seniority, role)
    return DEFAULT_HOURLY_RATE


def get_time_savings(
    activity: str,
    squad_config: Optional["SquadConfig"] = None,
) -> int:
    """
    Get time savings for an activity, optionally from squad config.

    Args:
        activity: Activity name (pr_review, spec_writing, etc.)
        squad_config: Optional SquadConfig from the project's squad

    Returns:
        Time savings in minutes
    """
    if squad_config:
        return squad_config.get_time_savings(activity)
    return TIME_SAVINGS.get(activity, 30)


def get_prevention_value(
    category: str,
    squad_config: Optional["SquadConfig"] = None,
) -> float:
    """
    Get prevention value for a category, optionally from squad config.

    Args:
        category: Category name (security_critical, bug_high, etc.)
        squad_config: Optional SquadConfig from the project's squad

    Returns:
        Prevention value in USD
    """
    if squad_config:
        return squad_config.get_prevention_value(category)
    return PREVENTION_VALUES.get(category, 1000.0)


def get_feature_multiplier(
    feature_type: FeatureType,
    squad_config: Optional["SquadConfig"] = None,
) -> float:
    """
    Get value multiplier for a feature type, optionally from squad config.

    Args:
        feature_type: The FeatureType enum value
        squad_config: Optional SquadConfig from the project's squad

    Returns:
        Multiplier value (1.0 is baseline)
    """
    if squad_config and squad_config.feature_multipliers:
        # Check if squad has a custom multiplier for this feature
        feature_key = feature_type.value
        if feature_key in squad_config.feature_multipliers:
            return squad_config.feature_multipliers[feature_key]
    return VALUE_MULTIPLIERS.get(feature_type, 1.0)


# =============================================================================
# Value Estimation Functions (Squad-aware)
# =============================================================================

def estimate_ideation_value(
    ideation_type: FeatureType,
    ideas_count: int,
    high_impact_count: int,
    hourly_rate: float = DEFAULT_HOURLY_RATE,
    squad_config: Optional["SquadConfig"] = None,
) -> Dict[ValueType, float]:
    """
    Estimate the value of ideation output.

    Value comes from:
    - DECISION: Identifying what to do/not do
    - PREVENTION: Finding issues before they become problems
    - KNOWLEDGE: Learning about the codebase

    Args:
        ideation_type: The type of ideation (security, performance, etc.)
        ideas_count: Total number of ideas generated
        high_impact_count: Number of high-impact ideas
        hourly_rate: Hourly rate for calculations (deprecated, use squad_config)
        squad_config: Optional SquadConfig for customized values
    """
    values = {}

    # Use squad config if provided, otherwise fall back to hourly_rate param or default
    effective_hourly_rate = get_hourly_rate(squad_config) if squad_config else hourly_rate

    # Base value: time saved on brainstorming
    brainstorm_minutes = get_time_savings("idea_generation", squad_config)
    brainstorm_hours = brainstorm_minutes / 60
    values[ValueType.KNOWLEDGE] = brainstorm_hours * effective_hourly_rate * 0.5

    # Decision value: each high-impact idea is valuable
    multiplier = get_feature_multiplier(ideation_type, squad_config)
    values[ValueType.DECISION] = high_impact_count * 50 * multiplier  # $50 per high-impact idea

    # Prevention value: especially for security/performance
    if ideation_type == FeatureType.IDEATION_SECURITY:
        prevention_val = get_prevention_value("security_medium", squad_config)
        values[ValueType.PREVENTION] = high_impact_count * prevention_val
    elif ideation_type == FeatureType.IDEATION_PERFORMANCE:
        prevention_val = get_prevention_value("performance_high", squad_config)
        values[ValueType.PREVENTION] = high_impact_count * prevention_val * 0.1

    return values


def estimate_roadmap_value(
    features_identified: int,
    features_rejected: int,
    avg_feature_cost: float = 5000.0,  # Average cost to implement a feature
    hourly_rate: float = DEFAULT_HOURLY_RATE,
    squad_config: Optional["SquadConfig"] = None,
) -> Dict[ValueType, float]:
    """
    Estimate the value of roadmap output.

    Value comes from:
    - DECISION: Prioritizing what to do first
    - PREVENTION: NOT doing low-value features (huge savings!)
    - KNOWLEDGE: Understanding the market/competitors

    Args:
        features_identified: Number of features identified
        features_rejected: Number of features rejected (not to be built)
        avg_feature_cost: Average cost to implement a feature
        hourly_rate: Hourly rate for calculations (deprecated, use squad_config)
        squad_config: Optional SquadConfig for customized values
    """
    values = {}

    # Use squad config if provided, otherwise fall back to hourly_rate param or default
    effective_hourly_rate = get_hourly_rate(squad_config) if squad_config else hourly_rate

    # Planning time saved
    planning_minutes = get_time_savings("roadmap_planning", squad_config)
    planning_hours = planning_minutes / 60
    values[ValueType.KNOWLEDGE] = planning_hours * effective_hourly_rate * 0.5

    # Decision value: prioritization matters
    values[ValueType.DECISION] = features_identified * 100  # $100 per prioritized feature

    # Prevention value: NOT building low-value features
    # This is the big one - if you decide not to build something, you save ALL of its cost
    values[ValueType.PREVENTION] = features_rejected * avg_feature_cost * 0.3  # 30% of avoided cost

    return values


def estimate_github_value(
    prs_reviewed: int = 0,
    issues_triaged: int = 0,
    issues_auto_fixed: int = 0,
    hourly_rate: float = DEFAULT_HOURLY_RATE,
    squad_config: Optional["SquadConfig"] = None,
) -> Dict[ValueType, float]:
    """
    Estimate the value of GitHub automation.

    Value comes from:
    - EXECUTION: Time saved on reviews and triage
    - PREVENTION: Issues caught before merge

    Args:
        prs_reviewed: Number of PRs reviewed
        issues_triaged: Number of issues triaged
        issues_auto_fixed: Number of issues auto-fixed
        hourly_rate: Hourly rate for calculations (deprecated, use squad_config)
        squad_config: Optional SquadConfig for customized values
    """
    values = {}

    # Use squad config if provided, otherwise fall back to hourly_rate param or default
    effective_hourly_rate = get_hourly_rate(squad_config) if squad_config else hourly_rate

    # Time saved on PR reviews
    pr_review_minutes = get_time_savings("pr_review", squad_config)
    pr_review_hours = (prs_reviewed * pr_review_minutes) / 60

    # Time saved on issue triage
    issue_triage_minutes = get_time_savings("issue_triage", squad_config)
    triage_hours = (issues_triaged * issue_triage_minutes) / 60

    values[ValueType.EXECUTION] = (pr_review_hours + triage_hours) * effective_hourly_rate

    # Auto-fixed issues have high value
    values[ValueType.DECISION] = issues_auto_fixed * 200  # $200 per auto-fixed issue

    return values
